function renderProduct(i,areaOverride){
 selectedIndex=i; renderProdList(); const p=products[i]; let calc='';
 if(p.calc==='top_conditions'){
    calc=commonAreaFields(areaOverride)+`<div class="choice-highlight"><div class="choice-title">Qual é a condição da estrutura?</div><div class="grid2">
      <div class="field"><label>Condição de exposição</label><select id="topCondition">
        <option value="2|2|2">Umidade de solo / água de percolação — 2,0 kg/m²</option>
        <option value="3|5|3 a 5">Pressão positiva até 25 m.c.a. — 3,0 a 5,0 kg/m²</option>
        <option value="4|5|4 a 5">Pressão negativa até 10 m.c.a. — 4,0 a 5,0 kg/m²</option>
      </select></div>
      <div class="field"><label>Embalagem (kg)</label><input id="pPack" type="number" value="18"></div>
    </div></div><div class="calc-help"><span>ℹ</span><div><b>Como a compra é calculada:</b> quando existe uma faixa de consumo, a calculadora mostra mínimo e máximo e usa o valor máximo para dimensionar a quantidade de embalagens.</div></div>`;
 }
 if(p.calc==='usage_select'){
    let opts='';
    if(p.name==='IMPERTUDO ULTRAFLEX UV') opts=`
      <option value="3">Áreas frias — 3,0 kg/m²</option>
      <option value="3">Sacadas e lajes pequenas — 3,0 kg/m²</option>
      <option value="4">Piscinas de concreto — 4,0 kg/m²</option>
      <option value="4">Piscinas enterradas — 4,0 kg/m²</option>
      <option value="4">Reservatórios — 4,0 kg/m²</option>
      <option value="4">Lajes expostas com tela — 4,0 kg/m²</option>`;
    if(p.name==='IMPERTUDO PAREDE PREMIUM') opts=`
      <option value="0.12">Selador — 120 g/m² (1 demão)</option>
      <option value="0.24">Impermeabilizante — 240 g/m² (2 demãos)</option>
      <option value="0.36">Acabamento — 360 g/m² (3 demãos)</option>`;
    calc=commonAreaFields(areaOverride)+`<div class="grid2"><div class="field"><label>Aplicação / finalidade</label><select id="usageCons">${opts}</select></div><div class="field"><label>Embalagem escolhida (kg)</label><input id="pPack" type="number" value="18"></div></div>`;
 }
 if(p.calc==='yield_range'){
    calc=commonAreaFields(areaOverride)+`<div class="grid2"><div class="field"><label>Superfície</label><select id="yieldUse">
      <option value="8|10">Telhas e tijolos — 8 a 10 m²/L</option>
      <option value="10|15">Concreto aparente e fibrocimento — 10 a 15 m²/L</option>
    </select></div><div class="field"><label>Embalagem de referência</label><select id="yieldPack"><option value="1">Pote 1 L</option><option value="5">Galão 5 L</option><option value="20">Balde 20 L</option></select></div></div>`;
 }
 if(p.calc==='pro_laje'){
    calc=`<div class="choice-highlight"><div class="choice-title">O que será calculado?</div><div class="grid2"><div class="field"><label>Aplicação</label><select id="proMode" onchange="toggleProLaje()"><option value="area">Impermeabilização de área — 3,5 kg/m²</option><option value="joint">Junta 1 × 1 cm — 143 g/m linear</option></select></div><div class="field"><label>Embalagem (kg)</label><select id="proPack"><option value="4.3">Galão 4,3 kg</option><option value="20">Lata 20 kg</option></select></div></div></div>
      <div id="proArea">${commonAreaFields(areaOverride)}</div>
      <div id="proJoint" class="hidden"><div class="grid2"><div class="field"><label>Comprimento total da junta (m)</label><input id="proJointM" type="number" value="20" step="0.01"></div><div class="field"><label>Margem adicional (%)</label><input id="proJointWaste" type="number" value="10"></div></div><div class="note">Consumo de 143 g/m linear válido para junta de referência com dimensão 1 cm × 1 cm.</div></div>`;
 }
 if(p.calc==='guided_range') calc=commonAreaFields(areaOverride)+`<div class="choice-highlight"><div class="choice-title">Selecione a solicitação</div><div class="grid2">${guidedSelectHTML(p,'guidedApp')}<div class="field"><label>Número de demãos</label><input id="guidedCoats" type="number" value="1" min="1" step="1"></div></div></div><div class="calc-help"><span>ℹ</span><div>O consumo é preenchido pela ficha rápida. Se o consumo estiver indicado <b>por demão</b>, o número de demãos entra automaticamente no quantitativo.</div></div>`;
 if(p.calc==='area') calc=commonAreaFields(areaOverride)+`<div class="grid2"><div class="field"><label>Consumo cadastrado</label><input id="pCons" value="${p.cons}" disabled></div><div class="field"><label>Tamanho da embalagem (kg)</label><input id="pPack" type="number" value="${parseFloat(p.pack)||18}" min="0" step="0.1"></div></div>`;
 if(p.calc==='area_range') calc=commonAreaFields(areaOverride)+`<div class="grid3"><div class="field"><label>Consumo mínimo (kg/m²)</label><input id="pMin" type="number" value="${p.consMin}" step="0.1"></div><div class="field"><label>Consumo máximo (kg/m²)</label><input id="pMax" type="number" value="${p.consMax}" step="0.1"></div><div class="field"><label>Embalagem escolhida (kg)</label><input id="pPack" type="number" value="18" step="0.1"></div></div>`;
 if(p.calc==='area_manual'||p.calc==='area_top') calc=commonAreaFields(areaOverride)+`<div class="grid2"><div class="field"><label>Consumo da ficha técnica (kg ou L por m²)</label><input id="pCons" type="number" value="${p.cons||''}" placeholder="Ex.: 0,5" step="0.01"></div><div class="field"><label>Conteúdo da embalagem (kg ou L)</label><input id="pPack" type="number" placeholder="Ex.: 18" step="0.01"></div></div>`;
 if(p.calc==='topflex') calc=commonAreaFields(areaOverride)+`<div class="grid3"><div class="field"><label>Aplicação</label><select id="pApp"><option value="3">Área fria — 3,0 kg/m²</option><option value="4">Piscina elevada/apoiada — 4,0 kg/m²</option><option value="4.5">Reservatório/piscina — 4,5 kg/m²</option></select></div><div class="field"><label>Embalagem (kg)</label><input id="pPack" type="number" value="18"></div><div class="field"><label><input id="pNegative" type="checkbox" style="width:auto"> Estrutura enterrada / pressão negativa</label></div></div>`;
 if(p.calc==='roll'||p.calc==='roll_manual') calc=commonAreaFields(areaOverride)+`<div class="grid2"><div class="field"><label>Área nominal por rolo (m²)</label><input id="pRoll" type="number" value="${p.rollArea||''}" placeholder="Ex.: 10" step="0.01"></div><div class="field"><label>Adicional para emendas/recortes já está na margem acima</label><input value="Use margem de 10% ou conforme paginação" disabled></div></div>`;
 if(p.calc==='joint') calc=`<div class="joint-mode"><div class="grid3"><div class="field"><label>Comprimento total da junta (m)</label><input id="jL" type="number" value="20" step="0.01"></div><div class="field"><label>Largura da junta (mm)</label><input id="jW" type="number" value="10" step="0.1"></div><div class="field"><label>Profundidade efetiva (mm)</label><input id="jD" type="number" value="10" step="0.1"></div><div class="field"><label>Nº de cordões / aplicações</label><input id="jPasses" type="number" value="1" min="1" step="1"></div><div class="field"><label>Margem para perdas (%)</label><input id="pWaste" type="number" value="10"></div><div class="field"><label>Calcular embalagem por</label><select id="jPackMode" onchange="toggleJointPackMode()"><option value="volume">Volume (mL)</option><option value="mass">Peso (g)</option></select></div><div class="field" id="jVolumePackField"><label>Bisnaga / sachê (mL)</label><select id="jPackMl"><option value="300">300 mL</option><option value="400">400 mL</option><option value="600">600 mL</option><option value="800">800 mL</option></select></div><div class="field hidden" id="jMassPackField"><label>Embalagem (g)</label><select id="jPackG"><option value="400">400 g</option><option value="800">800 g</option></select></div><div class="field hidden" id="jDensityField"><label>Densidade (g/mL)</label><input id="jDensity" type="number" step="0.01" placeholder="Conforme ficha técnica"></div></div><div class="pwa-hint"><span>↔</span><div>Volume = comprimento × largura × profundidade. Os tamanhos 300/400/600/800 são opções de cálculo; confirme a apresentação comercial do produto na ficha vigente.</div></div></div>`;
 if(p.calc==='joint_manual'||p.calc==='linear_manual') calc=`<div class="grid3"><div class="field"><label>Metragem linear necessária (m)</label><input id="linM" type="number" value="20"></div><div class="field"><label>Rendimento por embalagem/rolo (m)</label><input id="linYield" type="number" placeholder="Conforme ficha"></div><div class="field"><label>Margem (%)</label><input id="pWaste" type="number" value="5"></div></div>`;
 if(p.calc==='linear_or_area_manual') calc=`<div class="grid2"><div class="field"><label>Modo</label><select id="laMode"><option value="linear">Metro linear</option><option value="area">Área</option></select></div><div class="field"><label>Quantidade necessária (m ou m²)</label><input id="laQty" type="number" value="20"></div><div class="field"><label>Rendimento por rolo (m ou m²)</label><input id="laYield" type="number" placeholder="Conforme ficha"></div><div class="field"><label>Margem (%)</label><input id="pWaste" type="number" value="5"></div></div>`;
 if(p.calc==='volume_manual') calc=`<div class="grid3"><div class="field"><label>Comprimento do reparo (m)</label><input id="vL" type="number" value="1"></div><div class="field"><label>Largura (m)</label><input id="vW" type="number" value="1"></div><div class="field"><label>Espessura (mm)</label><input id="vD" type="number" value="20"></div><div class="field"><label>Consumo/rendimento do produto (kg/m³)</label><input id="vCons" type="number" placeholder="Conforme ficha"></div><div class="field"><label>Embalagem (kg)</label><input id="pPack" type="number" value="25"></div><div class="field"><label>Margem (%)</label><input id="pWaste" type="number" value="5"></div></div>`;
 if(p.calc==='concrete_dose') calc=`<div class="grid3"><div class="field"><label>Volume de concreto (m³)</label><input id="cVol" type="number" value="10"></div><div class="field"><label>Dosagem do produto (kg/m³)</label><input id="cDose" type="number" placeholder="Conforme ficha/projeto"></div><div class="field"><label>Embalagem (kg)</label><input id="pPack" type="number" placeholder="Peso da embalagem"></div></div>`;
 if(p.calc==='cement_percent') calc=`<div class="grid3"><div class="field"><label>Volume de concreto/argamassa (m³)</label><input id="cVol" type="number" value="10"></div><div class="field"><label>Consumo de cimento (kg/m³)</label><input id="cementM3" type="number" value="350"></div><div class="field"><label>Dosagem do produto (% sobre cimento)</label><input id="cPct" type="number" placeholder="Conforme ficha/projeto" step="0.01"></div><div class="field"><label>Embalagem (kg)</label><input id="pPack" type="number" placeholder="Peso"></div></div>`;
 if(p.calc==='cement_dose') calc=`<div class="grid3"><div class="field"><label>Quantidade de cimento (sacos de 50 kg)</label><input id="bags" type="number" value="10"></div><div class="field"><label>Dosagem por saco (mL ou kg)</label><input id="doseBag" type="number" placeholder="Conforme ficha"></div><div class="field"><label>Conteúdo da embalagem na mesma unidade</label><input id="pPack" type="number" placeholder="Ex.: 18.000 mL"></div></div>`;
 if(p.calc==='dilution') calc=`<div class="grid3"><div class="field"><label>Produto concentrado disponível (L)</label><input id="dProd" type="number" value="1"></div><div class="field"><label>Partes de produto</label><input id="dA" type="number" value="1"></div><div class="field"><label>Partes de água</label><input id="dB" type="number" value="${p.name.includes('CONCENTRADO')?7:2}"></div><div class="field"><label>Consumo da mistura pronta (L/m²) — opcional</label><input id="dCons" type="number" placeholder="Conforme ficha"></div></div>`;
 if(p.calc==='manual') calc=`<div class="grid3"><div class="field"><label>Quantidade da obra</label><input id="mQty" type="number" value="1"></div><div class="field"><label>Consumo por unidade de obra</label><input id="mCons" type="number" placeholder="Conforme ficha/projeto"></div><div class="field"><label>Conteúdo por embalagem</label><input id="pPack" type="number" placeholder="Mesma unidade do consumo"></div></div>`;
 $('#productPanel').innerHTML=`<div class="product-head"><div class="product-head-top"><div><h3>${p.name}</h3><span class="pill">${p.cat}</span></div>${techStatus(p)}</div><div class="mini">Tipo de cálculo: <b>${calcName(p.calc)}</b> • Embalagem: <b>${p.pack}</b></div></div>${techGuide(p)}${p.note?`<div class="info">${p.note}</div>`:''}${calc}<div class="actions"><button class="btn primary" onclick="calcProduct()">Calcular quantidade</button><a class="btn ghost" href="${p.url}" target="_blank" rel="noopener">Ver produto no site oficial</a></div><div id="pResult" class="result hidden"></div>`;
}
