const LOGO_DATA_URI=new URL('./assets/logo-impertudo.svg',location.href).href;
let quoteItems=[],deferredInstallPrompt=null,paymentMethod='pix';
function cleanText(s){return String(s||'').replace(/\s+/g,' ').trim();}
function money(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});}
function inferPackOptions(clone,metrics){
 const opts=[...clone.querySelectorAll('.pack-card')].map(card=>{const qtdText=cleanText(card.querySelector('.pack-qtd')?.textContent),name=cleanText(card.querySelector('.pack-name')?.textContent),detail=cleanText(card.querySelector('.pack-sub')?.textContent),qty=parseInt((qtdText.match(/\d+/)||['1'])[0])||1;return {qty,label:name||qtdText||'embalagem',detail};}).filter(x=>x.qty>0);
 if(!opts.length){const ps=clone.querySelector('.purchase-summary');if(ps){const strong=cleanText(ps.querySelector('strong')?.textContent),qty=parseInt((strong.match(/\d+/)||['1'])[0])||1,label=cleanText(strong.replace(/^\d+\s*/,''))||'embalagem';opts.push({qty,label,detail:cleanText(ps.querySelector('span')?.textContent)});}}
 if(!opts.length){const m=(metrics||[]).find(x=>/quantidade|embalagens|compra/i.test(x.label||'')&&/^\s*\d/.test(x.value||''));if(m){const mt=String(m.value).match(/^\s*(\d+(?:[.,]\d+)?)\s*(.*)$/);if(mt)opts.push({qty:Math.ceil(parseFloat(mt[1].replace(',','.'))),label:mt[2]||'un.',detail:''});}}
 return opts;
}
function extractResult(el){
 const clone=el.cloneNode(true);clone.querySelectorAll('.actions,.summary-actions,button').forEach(x=>x.remove());
 const metrics=[...clone.querySelectorAll('.kpi')].map(k=>({value:cleanText(k.firstElementChild?.textContent),label:cleanText(k.lastElementChild?.textContent)})).filter(x=>x.value);
 const packs=[...clone.querySelectorAll('.pack-card,.purchase-summary,.best-combo')].map(x=>cleanText(x.textContent)).filter(Boolean);return {metrics,packs,packOptions:inferPackOptions(clone,metrics),raw:cleanText(clone.textContent)};
}
function normalizeQuoteItem(it){it.packOptions=Array.isArray(it.packOptions)?it.packOptions:[];it.selectedPackIndex=Number.isInteger(it.selectedPackIndex)?it.selectedPackIndex:0;const opt=it.packOptions[it.selectedPackIndex]||it.packOptions[0];it.priceQty=Number(it.priceQty||opt?.qty||1);it.priceUnitLabel=it.priceUnitLabel||opt?.label||'un.';it.unitPrice=Number(it.unitPrice||0);return it;}
function loadQuote(){
 try{quoteItems=JSON.parse(localStorage.getItem('impertudo_quote_v8')||localStorage.getItem('impertudo_quote_v7')||'[]').map(normalizeQuoteItem);}catch(e){quoteItems=[];}
 try{const s=JSON.parse(localStorage.getItem('impertudo_proposal_settings_v8')||localStorage.getItem('impertudo_proposal_settings_v7')||'{}');paymentMethod=s.paymentMethod||'pix';if($('#quoteClient'))$('#quoteClient').value=s.client||'';if($('#quoteConsultant'))$('#quoteConsultant').value=s.consultant||'';if($('#cashDiscount'))$('#cashDiscount').value=s.discount??0;if($('#paymentNote'))$('#paymentNote').value=s.note||'';}catch(e){}
 renderQuote();setPaymentMethod(paymentMethod,false);
}
function saveQuote(){localStorage.setItem('impertudo_quote_v8',JSON.stringify(quoteItems));renderQuote();}
function saveProposalSettings(){localStorage.setItem('impertudo_proposal_settings_v8',JSON.stringify({client:cleanText($('#quoteClient')?.value),consultant:cleanText($('#quoteConsultant')?.value),discount:Math.max(0,Math.min(100,num('cashDiscount'))),note:cleanText($('#paymentNote')?.value),paymentMethod}));}
function addResultToQuote(kind){
 let title,category,el;if(kind==='product'){const p=products[selectedIndex];title=p.name;category=p.cat;el=$('#pResult');}else{title='Sistema de Reservatório';category='Reservatórios';el=$('#resResult');}
 if(!el||el.classList.contains('hidden')){alert('Calcule primeiro.');return;}const result=extractResult(el),first=result.packOptions?.[0];quoteItems.push(normalizeQuoteItem({id:Date.now()+Math.random(),title,category,...result,selectedPackIndex:0,priceQty:first?.qty||1,priceUnitLabel:first?.label||'un.',unitPrice:0,createdAt:new Date().toLocaleString('pt-BR')}));saveQuote();
}
function removeQuoteItem(id){quoteItems=quoteItems.filter(x=>x.id!==id);saveQuote();}
function clearQuote(){if(quoteItems.length&&confirm('Limpar todos os itens?')){quoteItems=[];saveQuote();}}
function updateQuotePack(id,index){const it=quoteItems.find(x=>x.id===id);if(!it)return;it.selectedPackIndex=Number(index)||0;const opt=it.packOptions[it.selectedPackIndex];if(opt){it.priceQty=Number(opt.qty)||1;it.priceUnitLabel=opt.label||'un.';}saveQuote();}
function updateQuoteQty(id,value){const it=quoteItems.find(x=>x.id===id);if(!it)return;it.priceQty=Math.max(0,parseFloat(value)||0);saveQuote();}
function updateUnitPrice(id,value){const it=quoteItems.find(x=>x.id===id);if(!it)return;it.unitPrice=Math.max(0,parseFloat(String(value).replace(',','.'))||0);saveQuote();}
function itemSubtotal(it){return (Number(it.priceQty)||0)*(Number(it.unitPrice)||0);}
function quoteGrossTotal(){return quoteItems.reduce((s,it)=>s+itemSubtotal(it),0);}
function cashDiscountPct(){return Math.max(0,Math.min(100,num('cashDiscount')));}
function quoteCashTotal(){return quoteGrossTotal()*(1-cashDiscountPct()/100);}
function setPaymentMethod(method,save=true){paymentMethod=method||'pix';['pix','dinheiro','cartao'].forEach(m=>$('#pay'+(m==='pix'?'Pix':m==='dinheiro'?'Cash':'Card'))?.classList.toggle('active',paymentMethod===m));updateCommercialTotals();if(save)saveProposalSettings();}
function updateCommercialTotals(){const gross=quoteGrossTotal(),pct=cashDiscountPct(),discount=gross*pct/100,cash=gross-discount;if($('#quoteGross'))$('#quoteGross').textContent=money(gross);if($('#quoteDiscountValue'))$('#quoteDiscountValue').textContent=money(discount);if($('#quoteDiscountPct'))$('#quoteDiscountPct').textContent=fmt(pct,1)+'% de desconto';if($('#quoteCashTotal'))$('#quoteCashTotal').textContent=money(cash);if($('#quoteCardTotal'))$('#quoteCardTotal').textContent=money(gross);const label=paymentMethod==='cartao'?'Cartão':paymentMethod==='dinheiro'?'Dinheiro':'PIX',final=paymentMethod==='cartao'?gross:cash,detail=paymentMethod==='cartao'?'sem desconto':pct>0?`com ${fmt(pct,1)}% de desconto`:'sem desconto';if($('#selectedPaymentSummary'))$('#selectedPaymentSummary').innerHTML=`Forma selecionada: <b>${label} — ${money(final)}</b> <span style="opacity:.75">(${detail})</span>`;}
function escHtml(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function renderQuote(){
 const count=$('#quoteCount');if(count)count.textContent=quoteItems.length;const empty=$('#quoteEmpty'),list=$('#quoteList');if(!list)return;empty?.classList.toggle('hidden',quoteItems.length>0);
 list.innerHTML=quoteItems.map((raw,i)=>{const it=normalizeQuoteItem(raw),subtotal=itemSubtotal(it),opts=it.packOptions||[],packSelect=opts.length?`<select onchange="updateQuotePack(${it.id},this.value)">${opts.map((o,idx)=>`<option value="${idx}" ${idx===it.selectedPackIndex?'selected':''}>${o.qty} × ${escHtml(o.label)}</option>`).join('')}</select>`:`<input value="${escHtml(it.priceUnitLabel||'un.')}" disabled>`;return `<div class="quote-item"><div class="quote-item-head"><div><h4>${i+1}. ${escHtml(it.title)}</h4><small>${escHtml(it.category||'')} • ${escHtml(it.createdAt||'')}</small></div><button class="quote-remove" onclick="removeQuoteItem(${it.id})">Remover</button></div>${it.metrics?.length?`<div class="quote-metrics">${it.metrics.map(m=>`<div class="quote-metric"><b>${escHtml(m.value)}</b><span>${escHtml(m.label)}</span></div>`).join('')}</div>`:''}${it.packs?.length?`<div class="quote-packs"><b>Quantitativo calculado</b><br>${it.packs.map(escHtml).join('<br>')}</div>`:''}<div class="quote-commercial"><div class="quote-commercial-grid"><div class="field"><label>Embalagem / unidade para orçamento</label>${packSelect}</div><div class="field"><label>Quantidade</label><input type="number" min="0" step="1" value="${it.priceQty||0}" onchange="updateQuoteQty(${it.id},this.value)"></div><div class="field"><label>Preço unitário (R$)</label><input type="number" min="0" step="0.01" value="${it.unitPrice||''}" placeholder="0,00" onchange="updateUnitPrice(${it.id},this.value)"></div><div class="item-subtotal"><span>Subtotal</span><b>${money(subtotal)}</b></div></div>${!it.unitPrice?'<div class="price-missing">Preço unitário ainda não informado.</div>':''}</div></div>`;}).join('');updateCommercialTotals();
}
function paymentLabel(){return paymentMethod==='cartao'?'Cartão (sem desconto)':paymentMethod==='dinheiro'?'Dinheiro à vista':'PIX à vista';}
function commercialLines(){const gross=quoteGrossTotal(),pct=cashDiscountPct(),cash=quoteCashTotal();return {gross,pct,cash,card:gross,selected:paymentMethod==='cartao'?gross:cash};}
function proposalText(){const client=cleanText($('#quoteClient')?.value),consult=cleanText($('#quoteConsultant')?.value),note=cleanText($('#paymentNote')?.value),c=commercialLines();let t='IMPERTUDO - PROPOSTA / RESUMO DE MATERIAIS\n';if(client)t+='Cliente/obra: '+client+'\n';if(consult)t+='Responsável: '+consult+'\n';t+='\n';quoteItems.forEach((it,i)=>{t+=`${i+1}. ${it.title}\n`;(it.metrics||[]).forEach(m=>t+=`• ${m.label}: ${m.value}\n`);t+=`• Orçamento: ${it.priceQty||0} × ${it.priceUnitLabel||'un.'} × ${money(it.unitPrice||0)}\n• Subtotal: ${money(itemSubtotal(it))}\n\n`;});t+=`CONDIÇÕES COMERCIAIS\nTotal sem desconto: ${money(c.gross)}\nÀ vista PIX/Dinheiro (${fmt(c.pct,1)}% desc.): ${money(c.cash)}\nCartão sem desconto: ${money(c.card)}\nForma selecionada: ${paymentLabel()} — ${money(c.selected)}\n`;if(note)t+=`Observação: ${note}\n`;return t+'\nEstimativa de pré-dimensionamento. Conferir ficha técnica vigente e condições da obra.';}
async function copyProposal(){if(!quoteItems.length){alert('Adicione algum cálculo.');return;}const t=proposalText();try{await navigator.clipboard.writeText(t);alert('Resumo copiado.');}catch(e){prompt('Copie o resumo:',t);}}
function shareWhatsApp(){if(!quoteItems.length){alert('Adicione algum cálculo.');return;}window.open('https://wa.me/?text='+encodeURIComponent(proposalText()),'_blank');}
function generateProposalPDF(){
 if(!quoteItems.length){alert('Adicione algum cálculo.');return;}const client=cleanText($('#quoteClient')?.value),consult=cleanText($('#quoteConsultant')?.value),note=cleanText($('#paymentNote')?.value),c=commercialLines(),w=window.open('','_blank');if(!w){alert('Libere pop-ups para gerar o PDF.');return;}
 const items=quoteItems.map((it,i)=>`<section class="item"><h2>${i+1}. ${escHtml(it.title)}</h2><div class="cat">${escHtml(it.category||'')}</div><div class="metrics">${(it.metrics||[]).map(m=>`<div><b>${escHtml(m.value)}</b><span>${escHtml(m.label)}</span></div>`).join('')}</div><div class="price-row"><div><span>Qtd.</span><b>${escHtml(it.priceQty||0)}</b></div><div><span>Unidade</span><b>${escHtml(it.priceUnitLabel||'un.')}</b></div><div><span>Preço unitário</span><b>${money(it.unitPrice||0)}</b></div><div><span>Subtotal</span><b>${money(itemSubtotal(it))}</b></div></div></section>`).join('');
 const commercial=`<section class="commercial"><h2>Condições comerciais</h2><div class="totals"><div><span>Total sem desconto</span><b>${money(c.gross)}</b></div><div><span>Desconto à vista</span><b>${fmt(c.pct,1)}%</b></div><div class="cash"><span>PIX / Dinheiro</span><b>${money(c.cash)}</b></div><div><span>Cartão</span><b>${money(c.card)}</b></div></div><p><strong>Forma selecionada:</strong> ${escHtml(paymentLabel())} — ${money(c.selected)}</p>${note?`<p><strong>Observação:</strong> ${escHtml(note)}</p>`:''}</section>`;
 w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Proposta IMPERTUDO</title><style>@page{size:A4;margin:13mm}body{font-family:Arial,sans-serif;color:#183229;margin:0}header{display:flex;justify-content:space-between;align-items:center;border-bottom:3px solid #087548;padding-bottom:11px;margin-bottom:16px}header img{height:55px;width:150px;object-fit:contain}h1{font-size:19px;color:#087548;margin:0}.meta{font-size:9px;color:#64766e;text-align:right}.item{border:1px solid #dce7e1;border-radius:9px;padding:11px;margin-bottom:9px;break-inside:avoid}h2{font-size:13px;margin:0}.cat{font-size:8px;color:#778880;margin:3px 0 8px}.metrics,.price-row,.totals{display:grid;grid-template-columns:repeat(4,1fr);gap:5px}.metrics{grid-template-columns:repeat(3,1fr)}.metrics div,.price-row div,.totals div{background:#f5f9f7;padding:7px;border-radius:6px}.metrics b,.price-row b,.totals b{display:block;color:#087548;font-size:10px}.metrics span,.price-row span,.totals span{font-size:7px;color:#667970}.price-row{margin-top:7px}.commercial{margin-top:13px;padding:12px;border:2px solid #087548;border-radius:9px;break-inside:avoid}.cash{background:#087548!important;color:#fff}.cash b,.cash span{color:#fff!important}.commercial p{font-size:9px}footer{margin-top:14px;border-top:1px solid #dce7e1;padding-top:7px;font-size:7px;color:#74857d}</style></head><body><header><img src="${LOGO_DATA_URI}"><div><h1>Proposta / Resumo de Materiais</h1><div class="meta">${client?'Cliente/obra: '+escHtml(client)+'<br>':''}${consult?'Responsável: '+escHtml(consult)+'<br>':''}${new Date().toLocaleString('pt-BR')}</div></div></header>${items}${commercial}<footer>Ferramenta de pré-dimensionamento IMPERTUDO. Conferir ficha técnica vigente, projeto e condições reais da obra.</footer><script>setTimeout(()=>window.print(),500)<\/script></body></html>`);w.document.close();
}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;$('#installAppBtn')?.classList.remove('hidden');});
async function installPWA(){if(!deferredInstallPrompt){alert('Depois de publicado em HTTPS, use a opção Instalar aplicativo do navegador.');return;}deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;$('#installAppBtn')?.classList.add('hidden');}
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
