/* V8.3 — inicialização e integração */
(function initV83(){
 const tags=[...document.querySelectorAll('.hero-tags .tag')],versionTag=tags.find(x=>/Versão/i.test(x.textContent||''));if(versionTag)versionTag.textContent='Versão 8.3 • estabilidade, offline e proposta revisada';
 const res=$('#resProduct');if(res&&![...res.options].some(o=>o.value==='top')){const opt=document.createElement('option');opt.value='top';opt.textContent='IMPERTUDO TOP';const manual=[...res.options].find(o=>o.value==='manual');res.insertBefore(opt,manual||null);}
 const grid=document.querySelector('.financial-grid');if(grid){grid.classList.add('financial-grid-v82');grid.innerHTML=`<div class="financial-card"><span>Total de tabela</span><b id="quoteGross">R$ 0,00</b><small>Antes dos descontos dos itens</small></div><div class="financial-card item-discount-card"><span>Descontos dos itens</span><b id="quoteItemDiscountTotal">R$ 0,00</b><small>Soma dos descontos item a item</small></div><div class="financial-card"><span>Base após itens</span><b id="quoteNetBase">R$ 0,00</b><small>Base comercial da proposta</small></div><div class="financial-card discount-card"><span>Desconto à vista</span><b id="quoteDiscountValue">R$ 0,00</b><small id="quoteDiscountPct">0%</small></div><div class="financial-card cash-card"><span>PIX / Dinheiro</span><b id="quoteCashTotal">R$ 0,00</b><small>Valor final à vista</small></div><div class="financial-card card-card"><span>Cartão</span><b id="quoteCardTotal">R$ 0,00</b><small>Sem desconto adicional à vista</small></div>`;}
 if(typeof window.__renderProductV8Original==='undefined'&&typeof renderProduct==='function'){window.__renderProductV8Original=renderProduct;renderProduct=function(...args){const out=window.__renderProductV8Original(...args);if($('#pAreaDynamic'))renderProductAreaFields();return out;};}
 try{if(typeof renderProduct==='function')renderProduct(selectedIndex,lastArea||'');}catch(e){console.warn('V8.3 product refresh',e);}
 try{if(typeof loadQuote==='function')loadQuote();}catch(e){console.warn('V8.3 quote refresh',e);}
})();
